run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - ineffassign
    - unused
    - gofmt

linters-settings:
  revive:
    rules:
      - name: var-naming
        severity: warning
