apiVersion: platform.upsidedown.io/v1alpha1
kind: TenantNamespace
metadata:
  name: testing
spec:
  tenantID: testing-ns

  # Grant namespace admin to these subjects (RBAC RoleBinding created by operator)
  adminSubjects:
    - kind: Group
      name: testing-ns-admins

  # Baseline controls the operator should enforce in the target namespace
  baselinePolicy:
    resourceQuota: true
    limitRange: true
    networkIsolation: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-admins
  namespace: tenant-testing-ns   # or whatever targetNamespace is
subjects:
  - kind: Group
    name: testing-ns-admins
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
