apiVersion: arbiter.io/v1alpha1
kind: TenantNamespace
metadata:
  name: upside-down
spec:
  tenantID: upsidedown

  # Explicit namespace name (clean + thematic)
  targetNamespace: hawkins-lab

  # Full control — “those who cross the gate”
  adminSubjects:
    - kind: Group
      name: hellfire-club

    - kind: User
      name: eleven@hawkins.local

    - kind: ServiceAccount
      name: demogorgon-bot
      namespace: hawkins-lab

  # Hawkins Lab security posture
  baselinePolicy:
    resourceQuota: true
    limitRange: true
    networkIsolation: true
    allowedIngressPorts:
      - 443
      - 8443
    resourceQuotaSpec:
      hard:
        requests.cpu: "3"
        requests.memory: 6Gi
        limits.cpu: "6"
        limits.memory: 12Gi
        pods: "75"
    limitRangeSpec:
      limits:
        - type: Container
          defaultRequest:
            cpu: 200m
            memory: 256Mi
          default:
            cpu: "1"
            memory: 1Gi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gate-operators
  namespace: hawkins-lab
  labels:
    arbiter.io/tenant: upsidedown
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: Group
    name: gate-operators
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: signal-observers
  namespace: hawkins-lab
  labels:
    arbiter.io/tenant: upsidedown
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: Group
    name: signal-watchers
    apiGroup: rbac.authorization.k8s.io
