apiVersion: platform.upsidedown.io/v1alpha1
kind: TenantNamespace
metadata:
  name: upside-down
spec:
  tenantID: upsidedown

  # Explicit namespace name (clean + thematic)
  targetNamespace: hawkins-lab

  # Full control — “those who cross the gate”
  adminSubjects:
    - kind: Group
      name: hellfire-club

    - kind: User
      name: eleven@hawkins.local

    - kind: ServiceAccount
      name: demogorgon-bot
      namespace: hawkins-lab

  # Hawkins Lab security posture
  baselinePolicy:
    resourceQuota: true
    limitRange: true
    networkIsolation: true
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gate-operators
  namespace: hawkins-lab
  labels:
    platform.upsidedown.io/tenant: upsidedown
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: Group
    name: gate-operators
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: signal-observers
  namespace: hawkins-lab
  labels:
    platform.upsidedown.io/tenant: upsidedown
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: Group
    name: signal-watchers
    apiGroup: rbac.authorization.k8s.io
