//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Baseline) DeepCopyInto(out *Baseline) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Baseline.
func (in *Baseline) DeepCopy() *Baseline {
	if in == nil {
		return nil
	}
	out := new(Baseline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Baseline) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaselineList) DeepCopyInto(out *BaselineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Baseline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaselineList.
func (in *BaselineList) DeepCopy() *BaselineList {
	if in == nil {
		return nil
	}
	out := new(BaselineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BaselineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaselinePolicy) DeepCopyInto(out *BaselinePolicy) {
	*out = *in
	if in.NetworkIsolation != nil {
		in, out := &in.NetworkIsolation, &out.NetworkIsolation
		*out = new(bool)
		**out = **in
	}
	if in.ResourceQuota != nil {
		in, out := &in.ResourceQuota, &out.ResourceQuota
		*out = new(bool)
		**out = **in
	}
	if in.LimitRange != nil {
		in, out := &in.LimitRange, &out.LimitRange
		*out = new(bool)
		**out = **in
	}
	if in.ResourceQuotaSpec != nil {
		in, out := &in.ResourceQuotaSpec, &out.ResourceQuotaSpec
		*out = new(corev1.ResourceQuotaSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LimitRangeSpec != nil {
		in, out := &in.LimitRangeSpec, &out.LimitRangeSpec
		*out = new(corev1.LimitRangeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedIngressPorts != nil {
		in, out := &in.AllowedIngressPorts, &out.AllowedIngressPorts
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaselinePolicy.
func (in *BaselinePolicy) DeepCopy() *BaselinePolicy {
	if in == nil {
		return nil
	}
	out := new(BaselinePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaselineSpec) DeepCopyInto(out *BaselineSpec) {
	*out = *in
	in.BaselinePolicy.DeepCopyInto(&out.BaselinePolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaselineSpec.
func (in *BaselineSpec) DeepCopy() *BaselineSpec {
	if in == nil {
		return nil
	}
	out := new(BaselineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaselineStatus) DeepCopyInto(out *BaselineStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaselineStatus.
func (in *BaselineStatus) DeepCopy() *BaselineStatus {
	if in == nil {
		return nil
	}
	out := new(BaselineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalIntegrations) DeepCopyInto(out *ExternalIntegrations) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalIntegrations.
func (in *ExternalIntegrations) DeepCopy() *ExternalIntegrations {
	if in == nil {
		return nil
	}
	out := new(ExternalIntegrations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Occupant) DeepCopyInto(out *Occupant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Occupant.
func (in *Occupant) DeepCopy() *Occupant {
	if in == nil {
		return nil
	}
	out := new(Occupant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Occupant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OccupantDefaulter) DeepCopyInto(out *OccupantDefaulter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OccupantDefaulter.
func (in *OccupantDefaulter) DeepCopy() *OccupantDefaulter {
	if in == nil {
		return nil
	}
	out := new(OccupantDefaulter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OccupantList) DeepCopyInto(out *OccupantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Occupant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OccupantList.
func (in *OccupantList) DeepCopy() *OccupantList {
	if in == nil {
		return nil
	}
	out := new(OccupantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OccupantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OccupantSpec) DeepCopyInto(out *OccupantSpec) {
	*out = *in
	if in.TargetNamespaces != nil {
		in, out := &in.TargetNamespaces, &out.TargetNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdoptedNamespaces != nil {
		in, out := &in.AdoptedNamespaces, &out.AdoptedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdminSubjects != nil {
		in, out := &in.AdminSubjects, &out.AdminSubjects
		*out = make([]RbacSubject, len(*in))
		copy(*out, *in)
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.ExternalIntegrations = in.ExternalIntegrations
	in.BaselinePolicy.DeepCopyInto(&out.BaselinePolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OccupantSpec.
func (in *OccupantSpec) DeepCopy() *OccupantSpec {
	if in == nil {
		return nil
	}
	out := new(OccupantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OccupantStatus) DeepCopyInto(out *OccupantStatus) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnabledCapabilities != nil {
		in, out := &in.EnabledCapabilities, &out.EnabledCapabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastReconciliationTime != nil {
		in, out := &in.LastReconciliationTime, &out.LastReconciliationTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OccupantStatus.
func (in *OccupantStatus) DeepCopy() *OccupantStatus {
	if in == nil {
		return nil
	}
	out := new(OccupantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RbacSubject) DeepCopyInto(out *RbacSubject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RbacSubject.
func (in *RbacSubject) DeepCopy() *RbacSubject {
	if in == nil {
		return nil
	}
	out := new(RbacSubject)
	in.DeepCopyInto(out)
	return out
}
